# Two stage bootloader (b0 + MCUboot)
SB_CONFIG_SECURE_BOOT_APPCORE=y
SB_CONFIG_BOOTLOADER_MCUBOOT=y

SB_CONFIG_MCUBOOT_MODE_SWAP_USING_MOVE=y

# app0 = image 0, app1 = image 1
# MCUboot adds its own s0/s1 pair as image 2
SB_CONFIG_MCUBOOT_UPDATEABLE_IMAGES=2
